CREATE TABLE `product` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `brand` enum('ADIDAS','CALVIN_KLEIN','COLCCI','CONVERSE','GUCCI','KENNER','LACOSTE','LOUIS_VUITTON','MIZUNO','NIKE','OAKLEY','OUS','PRADA','PUMA','QUICK_SILVER','TOMMY_HILFIGER') DEFAULT NULL,
  `category` enum('BLUSA','BONE','CALCA','CAMISA','CAMISETA','CHINELO','CROPPED','INTIMA','JAQUETA','MEIA','MOLETOM','REGATA','SAIA','SHORTS','TENIS','VESTIDO') DEFAULT NULL,
  `material` enum('ALGODAO','COURO','DRY_FIT','JEANS','MOLETOM','POLIESTER','PRIMEIRA_LINHA','SEGUNDA_LINHA','SOCIAL','TACTEL') DEFAULT NULL,
  `created` datetime(6) DEFAULT NULL,
  `last_update` datetime(6) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `price` float NOT NULL,
  `quantity` int NOT NULL,
  PRIMARY KEY (`id`)
)